### ISSUE TITLE
error with openGL when installed ubuntu 20.04

### ISSUE THREAD

**Issue by mytricker0** [angeluriot/Graphics_skeleton#2]
bash ./unix_launch.sh 

-- Found SFML 2.5.1 in /home/mytricker/opt/Graphics_skeleton-1.0/libraries/SFML/GCC/x64/lib/cmake/SFML
-- Found SFML 2.5.1 in /home/mytricker/opt/Graphics_skeleton-1.0/libraries/SFML/GCC/x64/lib/cmake/SFML
-- Configuring done
CMake Error at CMakeLists.txt:82 (target_link_libraries):
  Target "App" links to:

    OpenGL::OpenGL

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

CMake Error at libraries/CMakeLists.txt:64 (target_link_libraries):
  Target "Libraries" links to:

    OpenGL::OpenGL

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
[  2%] Building CXX object libraries/CMakeFiles/Libraries.dir/ImGui/imgui.cpp.o
[  5%] Building CXX object libraries/CMakeFiles/Libraries.dir/ImGui/imgui_draw.cpp.o
[  7%] Building CXX object libraries/CMakeFiles/Libraries.dir/ImGui/imgui_tables.cpp.o
[ 10%] Building CXX object libraries/CMakeFiles/Libraries.dir/ImGui/imgui_widgets.cpp.o
[ 12%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/cameras/Camera.cpp.o
[ 15%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/cameras/Camera2D.cpp.o
[ 17%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/cameras/OrthographicCamera.cpp.o
[ 20%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/cameras/PerspectiveCamera.cpp.o
[ 23%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/controllers/Controller.cpp.o
[ 25%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/controllers/DragController.cpp.o
[ 28%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/controllers/FlyController.cpp.o
[ 30%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/controllers/OrbitController.cpp.o
[ 33%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/dimension3D.cpp.o
[ 35%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/lights/AmbientLight.cpp.o
[ 38%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/lights/DirectionalLight.cpp.o
[ 41%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/lights/Light.cpp.o
[ 43%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/lights/PointLight.cpp.o
[ 46%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/objects/Material.cpp.o
[ 48%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/objects/Mesh.cpp.o
[ 51%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/objects/Object.cpp.o
[ 53%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/opengl/FrameBuffer.cpp.o
[ 56%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/opengl/Shader.cpp.o
[ 58%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/opengl/Texture.cpp.o
[ 61%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/opengl/VertexBuffer.cpp.o
[ 64%] Building CXX object libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/utils/Color.cpp.o
/home/mytricker/opt/Graphics_skeleton-1.0/libraries/Dimension3D/sources/utils/Color.cpp:1:10: fatal error: dim/Dimension3D.hpp: No such file or directory
    1 | #include "dim/Dimension3D.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [libraries/CMakeFiles/Libraries.dir/build.make:426: libraries/CMakeFiles/Libraries.dir/Dimension3D/sources/utils/Color.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:126: libraries/CMakeFiles/Libraries.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by angeluriot** [comment]
Fixed 👍
